/*
Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// DO NOT EDIT THIS FILE: Generated by tool/loader.dart

part of '../stopwords.g.dart';

const Set<String> _ukStopwords = {
  r'авжеж',
  r'адже',
  r'але',
  r'б',
  r'без',
  r'був',
  r'була',
  r'були',
  r'було',
  r'бути',
  r'більш',
  r'вам',
  r'вас',
  r'весь',
  r'вздовж',
  r'ви',
  r'вниз',
  r'внизу',
  r'вона',
  r'вони',
  r'воно',
  r'все',
  r'всередині',
  r'всіх',
  r'від',
  r'він',
  r'да',
  r'давай',
  r'давати',
  r'де',
  r'дещо',
  r'для',
  r'до',
  r'з',
  r'завжди',
  r'замість',
  r'й',
  r'коли',
  r'ледве',
  r'майже',
  r'ми',
  r'навколо',
  r'навіть',
  r'нам',
  r'от',
  r'отже',
  r'отож',
  r'поза',
  r'про',
  r'під',
  r'та',
  r'так',
  r'такий',
  r'також',
  r'те',
  r'ти',
  r'тобто',
  r'тож',
  r'тощо',
  r'хоча',
  r'це',
  r'цей',
  r'чи',
  r'чого',
  r'що',
  r'як',
  r'який',
  r'якої',
  r'є',
  r'із',
  r'інших',
  r'їх',
  r'її',
};
