/*
Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// DO NOT EDIT THIS FILE: Generated by tool/loader.dart

part of '../stopwords.g.dart';

const Set<String> _zuStopwords = {
  r'futhi',
  r'kahle',
  r'kakhulu',
  r'kanye',
  r'khona',
  r'kodwa',
  r'kungani',
  r'kusho',
  r'la',
  r'lakhe',
  r'lapho',
  r'mina',
  r'ngesikhathi',
  r'nje',
  r'phansi',
  r'phezulu',
  r'u',
  r'ukuba',
  r'ukuthi',
  r'ukuze',
  r'uma',
  r'wahamba',
  r'wakhe',
  r'wami',
  r'wase',
  r'wathi',
  r'yakhe',
  r'zakhe',
  r'zonke',
};
