/*
Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

// DO NOT EDIT THIS FILE: Generated by tool/loader.dart

part 'stopwords/af.g.dart';
part 'stopwords/ar.g.dart';
part 'stopwords/bg.g.dart';
part 'stopwords/bn.g.dart';
part 'stopwords/br.g.dart';
part 'stopwords/ca.g.dart';
part 'stopwords/cs.g.dart';
part 'stopwords/da.g.dart';
part 'stopwords/de.g.dart';
part 'stopwords/el.g.dart';
part 'stopwords/en.g.dart';
part 'stopwords/eo.g.dart';
part 'stopwords/es.g.dart';
part 'stopwords/et.g.dart';
part 'stopwords/eu.g.dart';
part 'stopwords/fa.g.dart';
part 'stopwords/fi.g.dart';
part 'stopwords/fr.g.dart';
part 'stopwords/ga.g.dart';
part 'stopwords/gl.g.dart';
part 'stopwords/gu.g.dart';
part 'stopwords/ha.g.dart';
part 'stopwords/he.g.dart';
part 'stopwords/hi.g.dart';
part 'stopwords/hr.g.dart';
part 'stopwords/hu.g.dart';
part 'stopwords/hy.g.dart';
part 'stopwords/id.g.dart';
part 'stopwords/it.g.dart';
part 'stopwords/ja.g.dart';
part 'stopwords/ko.g.dart';
part 'stopwords/ku.g.dart';
part 'stopwords/la.g.dart';
part 'stopwords/lt.g.dart';
part 'stopwords/lv.g.dart';
part 'stopwords/mr.g.dart';
part 'stopwords/ms.g.dart';
part 'stopwords/nl.g.dart';
part 'stopwords/no.g.dart';
part 'stopwords/pl.g.dart';
part 'stopwords/pt.g.dart';
part 'stopwords/ro.g.dart';
part 'stopwords/ru.g.dart';
part 'stopwords/sk.g.dart';
part 'stopwords/sl.g.dart';
part 'stopwords/so.g.dart';
part 'stopwords/st.g.dart';
part 'stopwords/sv.g.dart';
part 'stopwords/sw.g.dart';
part 'stopwords/th.g.dart';
part 'stopwords/tl.g.dart';
part 'stopwords/tr.g.dart';
part 'stopwords/uk.g.dart';
part 'stopwords/ur.g.dart';
part 'stopwords/vi.g.dart';
part 'stopwords/yo.g.dart';
part 'stopwords/zh.g.dart';
part 'stopwords/zu.g.dart';

/// Stop-word sets for 58 languages, keyed by IETF language code.
///
/// Obtain an instance via [getStopWords]:
///
/// ```dart
/// final stopWords = getStopWords(Locale.parse('en'));
/// final filtered = tokens
///     .where((t) => !stopWords.listing.contains(t))
///     .toList();
/// ```
enum Stopwords {
  af('af', _afStopwords),
  ar('ar', _arStopwords),
  bg('bg', _bgStopwords),
  bn('bn', _bnStopwords),
  br('br', _brStopwords),
  ca('ca', _caStopwords),
  cs('cs', _csStopwords),
  da('da', _daStopwords),
  de('de', _deStopwords),
  el('el', _elStopwords),
  en('en', _enStopwords),
  eo('eo', _eoStopwords),
  es('es', _esStopwords),
  et('et', _etStopwords),
  eu('eu', _euStopwords),
  fa('fa', _faStopwords),
  fi('fi', _fiStopwords),
  fr('fr', _frStopwords),
  ga('ga', _gaStopwords),
  gl('gl', _glStopwords),
  gu('gu', _guStopwords),
  ha('ha', _haStopwords),
  he('he', _heStopwords),
  hi('hi', _hiStopwords),
  hr('hr', _hrStopwords),
  hu('hu', _huStopwords),
  hy('hy', _hyStopwords),
  id('id', _idStopwords),
  it('it', _itStopwords),
  ja('ja', _jaStopwords),
  ko('ko', _koStopwords),
  ku('ku', _kuStopwords),
  la('la', _laStopwords),
  lt('lt', _ltStopwords),
  lv('lv', _lvStopwords),
  mr('mr', _mrStopwords),
  ms('ms', _msStopwords),
  nl('nl', _nlStopwords),
  no('no', _noStopwords),
  pl('pl', _plStopwords),
  pt('pt', _ptStopwords),
  ro('ro', _roStopwords),
  ru('ru', _ruStopwords),
  sk('sk', _skStopwords),
  sl('sl', _slStopwords),
  so('so', _soStopwords),
  st('st', _stStopwords),
  sv('sv', _svStopwords),
  sw('sw', _swStopwords),
  th('th', _thStopwords),
  tl('tl', _tlStopwords),
  tr('tr', _trStopwords),
  uk('uk', _ukStopwords),
  ur('ur', _urStopwords),
  vi('vi', _viStopwords),
  yo('yo', _yoStopwords),
  zh('zh', _zhStopwords),
  zu('zu', _zuStopwords);

  const Stopwords(this.languageCode, this.listing);

  /// The set of stop words for this language.
  final Set<String> listing;

  /// The IETF language code identifying this stop-word set (e.g. `'en'`, `'fr'`).
  final String languageCode;
}
