/*
 Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 */

import 'dart:convert';
import 'dart:io';

import 'package:betto_builder_tools/betto_builder_tools.dart';
import 'package:code_builder/code_builder.dart';

final copyrightHeader = '''
 Copyright 2026 The Authors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
''';
const downloadUrl =
    'https://raw.githubusercontent.com/stopwords-iso/stopwords-iso/'
    'refs/heads/master/stopwords-iso.json';

const outputFilePath = 'lib/src/stopwords.g.dart';
const partDirPath = 'lib/src/stopwords';
final dataOutputFile = File('stopwords-iso.json');

void main(List<String> args) {
  dataOutputFile.parent.create(recursive: true);
  print('Data files will be placed in ${dataOutputFile.absolute.path}');

  loadData(
    dataOutputFile.absolute.path,
    downloadUrl,
    compression: CompressionType.none,
  ).then((data) {
    final Map<String, dynamic> listing = json.decode(data);

    buildStopwordRegistry(listing, outputFilePath);
  });
}

void buildStopwordRegistry(
  Map<String, dynamic> listing,
  String outputFilePath,
) {
  Directory(partDirPath).createSync(recursive: true);

  final sortedEntries = listing.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));

  // One part file per language containing the word-set constant.
  for (final entry in sortedEntries) {
    _buildLanguagePartFile(entry.key, Set.from(entry.value));
  }

  // Main file: part directives + enum referencing per-language constants.
  final mainLib = Library(
    (b) => b
      ..generatedByComment =
          'DO NOT EDIT THIS FILE: Generated by tool/loader.dart'
      ..directives.addAll(
        sortedEntries.map((e) => Directive.part('stopwords/${e.key}.g.dart')),
      )
      ..body.add(
        Enum(
          (eb) => eb
            ..name = 'Stopwords'
            ..docs.addAll([
              '/// Stop-word sets for 58 languages, keyed by IETF language code.',
              '///',
              '/// Obtain an instance via [getStopWords]:',
              '///',
              '/// ```dart',
              '/// final stopWords = getStopWords(Locale.parse(\'en\'));',
              '/// final filtered = tokens',
              '///     .where((t) => !stopWords.listing.contains(t))',
              '///     .toList();',
              '/// ```',
            ])
            ..fields.addAll([
              Field(
                (b) => b
                  ..name = 'listing'
                  ..docs.add('/// The set of stop words for this language.')
                  ..type = refer('Set<String>')
                  ..modifier = FieldModifier.final$,
              ),
              Field(
                (b) => b
                  ..name = 'languageCode'
                  ..docs.add(
                    '/// The IETF language code identifying this stop-word set (e.g. `\'en\'`, `\'fr\'`).',
                  )
                  ..type = refer('String')
                  ..modifier = FieldModifier.final$,
              ),
            ])
            ..constructors.add(
              Constructor(
                (b) => b
                  ..constant = true
                  ..requiredParameters.addAll([
                    Parameter(
                      (v) => v
                        ..name = 'languageCode'
                        ..toThis = true
                        ..named = false,
                    ),
                    Parameter(
                      (v) => v
                        ..name = 'listing'
                        ..toThis = true
                        ..named = false,
                    ),
                  ]),
              ),
            )
            ..values.addAll(
              sortedEntries.map(
                (entry) => EnumValue(
                  (b) => b
                    ..name = entry.key
                    ..arguments.addAll([
                      literal(entry.key),
                      refer('_${entry.key}Stopwords'),
                    ]),
                ),
              ),
            ),
        ),
      ),
  );

  final emitter = DartEmitter.scoped();
  final code =
      '/*\n${copyrightHeader.trim()}\n */\n\n${mainLib.accept(emitter)}';
  File(outputFilePath).writeAsStringSync(dartfmt.format(code));
  print('Generated: $outputFilePath');
}

void _buildLanguagePartFile(String lang, Set<dynamic> words) {
  final partLib = Library(
    (b) => b
      ..generatedByComment =
          'DO NOT EDIT THIS FILE: Generated by tool/loader.dart'
      ..directives.add(Directive.partOf('../stopwords.g.dart'))
      ..body.add(
        Field(
          (b) => b
            ..name = '_${lang}Stopwords'
            ..type = refer('Set<String>')
            ..modifier = FieldModifier.constant
            ..assignment = literalSet(
              words.map(
                (v) => v.contains("'")
                    ? literal('$v')
                    : literalString(v as String, raw: true),
              ),
            ).code,
        ),
      ),
  );

  final emitter = DartEmitter.scoped();
  final code =
      '/*\n${copyrightHeader.trim()}\n */\n\n${partLib.accept(emitter)}';
  File('$partDirPath/$lang.g.dart').writeAsStringSync(dartfmt.format(code));
  print('Generated: $partDirPath/$lang.g.dart');
}
